version: '2.1'
volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  
  fhirkeycloak:
    image: vasdvp/lighthouse-fhir-keycloak:latest
    # command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    #volumes:
    #  - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=deviam
      - KEYCLOAK_PASSWORD=deviam
      - FHIR_AUD_ISSUER=http://docker.for.mac.localhost:9080/auth/realms/fhirdev/v1
      - DB_VENDOR-POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE-keycloak
      - DB_USER-keycloak
      - DB_SCHEMA: public
      - DB_PASSWORD: password
  ports:
      - 8080:8080
      # - 9443:9443
      # - 10990:10990
      
